### ISSUE TITLE
Error specifying custom job type 

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/CAT#171]
When calling CAT with the following input:
```yml
  path: "."

  input_cores:
     - "[H]Cl"

  input_ligands:
    - "{smile}"

  optional:
      qd:
        construct_qd: False
      ligand:
        cosmo-rs: True
        cdft: True
        functional_groups: ['O(C=O)[H]']
        optimize:
          job2: ADFJob
          s2:
            input:
              xc:
                hybrid:
                  b3lyp
              basis:
                type: DZP
                core: None
                createoutput: None
```
CAT produces the following erroneous ADF input:
```
basis
  core None
  createoutput None
  type DZP
end

charge -1

geometry
  optim delocal
end

numericalquality good

scf
  converge 1e-6
  iterations 100
end

xc
  hybrid b3lyp
  lda
end
```
Where the lda functional has been added even though the user have defined a functional
