### ISSUE TITLE
optional.ligand.anchor.mean

### ISSUE THREAD

**Issue by juliette1996** [nlesc-nano/CAT#251]
Hi there,

sorry to disturb but we are facing some troubles with the optional.ligand.anchor.mean option. 

In particular we are trying to attach the two oxygens of a carboxylic acid to an In atom using the following the incl3.xyz core file:
```
4
 
In     0.000000     0.000000     0.000000
Cl     0.000000     0.000000     2.410000
Cl     2.272173     0.000000    -0.803325
Cl    -1.514773     0.000000    -1.874450
```

and input file:
``` yaml
input_cores:
    - incl3.xyz:
        guess_bonds: False

input_ligands:
    - CCCC(=O)O

optional:
    core:
        dirname: core
        anchor: Cl

    ligand:
        dirname: ligand
        anchor:
             group: "[H]OC(=O)"  # Remove H and attach at the mean position of both oxygens
             group_idx: [1, 3]
             remove: 0
             kind: mean
        optimize: False
        split: False
```

The program seems to recognize that two oxygens are to be attached (the qd file name is in fact Cl3In1__3_CCCC[=O][O-]@O5O6.xyz) but only one oxygen is actually anchored instead of the "mean" position...

can you please have a look at this?

thanks in advance! :)
