### ISSUE TITLE
Construct quantum-dots with more than one type of ligand

### ISSUE THREAD

**Issue by BvB93** [nlesc-nano/CAT#91]
* Construct quantum-dots with more than one type of ligand.
* Initially these structures will not be supported for the [Nano-CAT](https://github.com/nlesc-nano/nano-CAT) woorkflows.
This might be changed at a later date.

**Comment by BvB93** [comment]
Proposed syntax:
```
optional:
    core:
        symbol: 'Cl'
        multi_ligand:
            f: [0.3, 0.2, 0.1, 0.05]
            mode: 'uniform'
            ligands:
                - 'OCCCCCCCCCC'
                - 'OCCCCCCC'
                - 'OCCCC'
```

and / or
```
optional:
    core:
        symbol: 'Cl'
        multi_ligand:
            symbol: ['F', 'Br', 'I']
            ligands:
                - 'OCCCCCCCCCC'
                - 'OCCCCCCC'
                - 'OCCCC'
```
